# Generated by Django 4.1.7 on 2023-07-25 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyShippingTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('corporate_name', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(blank=True, max_length=150, verbose_name='Nome Fantasia')),
                ('state_registration', models.CharField(blank=True, max_length=35, verbose_name='Inscrição Estadual')),
                ('service_kind', models.CharField(blank=True, max_length=25, verbose_name='Tipo de Serviço')),
                ('value_shipping_int', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do Frete')),
                ('value_shipping_perc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Frete %')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data da Criação')),
            ],
            options={
                'verbose_name_plural': 'Transportadora',
                'ordering': ['corporate_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(max_length=5, verbose_name='CIF ou FOB')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('corporate_name', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(blank=True, max_length=150, verbose_name='Nome Fantasia')),
                ('state_registration', models.CharField(blank=True, max_length=35, verbose_name='Inscrição Estadual')),
                ('service_kind', models.CharField(blank=True, max_length=25, verbose_name='Tipo de Serviço')),
                ('need_schedule_collection', models.BooleanField(verbose_name='Necessário Agendamento Coleta')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Fornecedor',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='MainCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('corporate_name', models.CharField(max_length=45, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(blank=True, max_length=75, verbose_name='Nome Fantasia')),
                ('status', models.BooleanField(default=True, verbose_name='Empresa Ativa')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name_plural': 'Lojas ou Filiais',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45, unique=True, verbose_name='Descrição')),
                ('observation', models.CharField(blank=True, max_length=90, verbose_name='Observação')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name_plural': 'Status do Agendamento',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, verbose_name='Tipo de Veículo')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Descrição')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data da Criação')),
            ],
            options={
                'verbose_name_plural': 'Veículos',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='VehiclesListCompanyTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Descrição')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_company_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.companyshippingtransport', verbose_name='Transportadora')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.vehicles', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name_plural': 'Lista de Veículos Transportado',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='VehiclesListCompanySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Descrição')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_company_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.companysupplier', verbose_name='Fornecedor')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.vehicles', verbose_name='Veículo')),
            ],
            options={
                'verbose_name_plural': 'Lista de Veículos Fornecedor',
                'ordering': ['id_company_supplier'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Hora da Entrega')),
                ('date', models.DateField(verbose_name='Data da Entrega')),
                ('boolManyNfe', models.BooleanField(blank=True, default=False, verbose_name='NfeDetalhada?')),
                ('count_nfe', models.IntegerField(blank=True, verbose_name='Quantidade de Notas')),
                ('count_fullness', models.IntegerField(blank=True, verbose_name='Quantidade de Volumes')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_company_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.companysupplier', verbose_name='Fornecedor')),
                ('id_company_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.companyshippingtransport', verbose_name='Transportadora')),
                ('id_main_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.maincompany', verbose_name='Empresa Agendada')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.schedulestatus', verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Agenda de Entregas',
                'ordering': ['date', 'hour'],
            },
        ),
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfe_danfe', models.CharField(max_length=75, unique=True, verbose_name='DANFE')),
                ('nfe_number', models.CharField(max_length=75, verbose_name='Numero da NFe')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação')),
                ('id_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.schedule', verbose_name='ID Agendamento')),
            ],
            options={
                'verbose_name_plural': 'Lista de Notas Fiscais',
                'ordering': ['id_schedule', 'date_create'],
            },
        ),
        migrations.CreateModel(
            name='ContactCompanyTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_number', models.CharField(max_length=25, verbose_name='Nrº Agendamento')),
                ('representative_number', models.CharField(max_length=25, verbose_name='Nrº Representante')),
                ('shipping_company_number', models.CharField(max_length=25, verbose_name='Nrº Transportadora')),
                ('citizen_service_number', models.CharField(max_length=25, verbose_name='Nrº SAC')),
                ('email_adder', models.CharField(max_length=80, verbose_name='E-mail')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.companyshippingtransport', verbose_name='Transportadora')),
            ],
            options={
                'verbose_name_plural': 'Contatos Transportadoras',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='ContactCompanySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_number', models.CharField(blank=True, max_length=25, verbose_name='Nrº Agendamento')),
                ('representative_number', models.CharField(blank=True, max_length=25, verbose_name='Nrº Representante')),
                ('supplier_company_number', models.CharField(blank=True, max_length=25, verbose_name='Nrº Fornecedor')),
                ('citizen_service_number', models.CharField(blank=True, max_length=25, verbose_name='Nrº SAC')),
                ('email_adder', models.CharField(max_length=80, verbose_name='E-mail')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.companysupplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Contatos Fornecedor',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='AddressCompanyTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=75, verbose_name='Bairro')),
                ('number', models.CharField(max_length=75, verbose_name='Número')),
                ('city', models.CharField(max_length=75, verbose_name='Cidade')),
                ('reference', models.CharField(max_length=75, verbose_name='Referencia')),
                ('zip_code', models.CharField(max_length=75, verbose_name='CEP')),
                ('latitude', models.CharField(max_length=75, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=75, verbose_name='Longitude')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.companyshippingtransport', verbose_name='Transportadora')),
            ],
            options={
                'verbose_name_plural': 'Endereços Transportadora',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='AddressCompanySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=75, verbose_name='Bairro')),
                ('number', models.CharField(max_length=75, verbose_name='Número')),
                ('city', models.CharField(max_length=75, verbose_name='Cidade')),
                ('reference', models.CharField(max_length=75, verbose_name='Referencia')),
                ('zip_code', models.CharField(max_length=75, verbose_name='CEP')),
                ('latitude', models.CharField(max_length=75, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=75, verbose_name='Longitude')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id_company_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_scheduling.companysupplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Endereços Fornecedor',
                'ordering': ['date_create'],
            },
        ),
    ]
