# Generated by Django 4.1.7 on 2023-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='boolManyNfe',
        ),
        migrations.AlterField(
            model_name='addresscompanysupplier',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='addresscompanytransport',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companyshippingtransport',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação'),
        ),
        migrations.AlterField(
            model_name='companysupplier',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactcompanysupplier',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactcompanytransport',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maincompany',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedulestatus',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Criação'),
        ),
        migrations.AlterField(
            model_name='vehicleslistcompanysupplier',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicleslistcompanytransport',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
