# Generated by Django 4.1.7 on 2023-08-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_scheduling', '0002_remove_schedule_boolmanynfe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysupplier',
            name='vehicle_list',
            field=models.ManyToManyField(to='cloud_scheduling.vehicles'),
        ),
    ]
