# Generated by Django 4.2.5 on 2023-10-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_home', '0002_delete_ratingbar'),
        ('cloud_scheduling', '0003_companysupplier_vehicle_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id_main_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_home.company', verbose_name='Empresa Agendada'),
        ),
    ]
