# Generated by Django 4.2.5 on 2023-10-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_scheduling', '0004_alter_schedule_id_main_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCompany',
        ),
    ]
