# Generated by Django 4.1.7 on 2023-07-25 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratingbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(blank=True, db_column='NOTA', null=True)),
                ('comentario', models.TextField(blank=True, db_column='COMENTARIO', null=True)),
                ('data', models.DateField(blank=True, db_column='DATA', null=True)),
            ],
            options={
                'db_table': 'nowa_ratingbar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=25)),
                ('corporate_name', models.CharField(blank=True, max_length=45)),
                ('fantasy_name', models.CharField(blank=True, max_length=45)),
                ('description', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=125, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotfixLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('details', models.TextField(verbose_name='Descrição')),
                ('version', models.CharField(max_length=20, verbose_name='Versão')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name_plural': 'Lista de Atualização',
            },
        ),
        migrations.CreateModel(
            name='SuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=45, verbose_name='Usuario')),
                ('suggestion', models.TextField(verbose_name='Sugestão')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name_plural': 'Lista de Sugestão',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=125, unique=True)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_home.departament')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=45)),
                ('account_last_name', models.CharField(max_length=45)),
                ('account_email', models.CharField(max_length=150)),
                ('account_password', models.CharField(max_length=255)),
                ('account_dtcreate', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_dtedit', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_last_ip', models.CharField(blank=True, max_length=30)),
                ('account_last_session_name', models.CharField(blank=True, max_length=30)),
                ('account_disable', models.BooleanField(default=False)),
                ('account_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_home.company')),
                ('account_depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_home.departament')),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cloud_home.group')),
            ],
        ),
    ]
