# Generated by Django 4.1.7 on 2023-08-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratingbar',
        ),
    ]
