# Generated by Django 4.2.5 on 2023-10-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_home', '0002_delete_ratingbar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['status'], 'verbose_name_plural': 'Empresa'},
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Empresa Ativa'),
        ),
    ]
