# Generated by Django 4.2.4 on 2023-08-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCloudDash000001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=80, null=True)),
                ('vlrvda', models.FloatField(blank=True, null=True)),
                ('custovda', models.FloatField(blank=True, null=True)),
                ('vlrdev', models.FloatField(blank=True, null=True)),
                ('custodev', models.FloatField(blank=True, null=True)),
                ('vdaliq', models.FloatField(blank=True, null=True)),
                ('custoliq', models.FloatField(blank=True, null=True)),
                ('margem', models.FloatField(blank=True, null=True)),
                ('direto', models.FloatField(blank=True, null=True)),
                ('lucro', models.FloatField(blank=True, null=True)),
                ('perclucro', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ti_api_dashboard_id_00001',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiCloudDash000002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=40, null=True)),
                ('vlrvda', models.FloatField(blank=True, null=True)),
                ('custovda', models.FloatField(blank=True, null=True)),
                ('vlrdev', models.FloatField(blank=True, null=True)),
                ('custodev', models.FloatField(blank=True, null=True)),
                ('vdaliq', models.FloatField(blank=True, null=True)),
                ('custoliq', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ti_api_dashboard_id_00002',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiCloudDash000003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=121, null=True)),
                ('vlrvda', models.FloatField(blank=True, null=True)),
                ('custovda', models.FloatField(blank=True, null=True)),
                ('vlrdev', models.FloatField(blank=True, null=True)),
                ('custodev', models.FloatField(blank=True, null=True)),
                ('vdaliq', models.FloatField(blank=True, null=True)),
                ('custoliq', models.FloatField(blank=True, null=True)),
                ('margem', models.FloatField(blank=True, null=True)),
                ('direto', models.FloatField(blank=True, null=True)),
                ('lucro', models.FloatField(blank=True, null=True)),
                ('perclucro', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ti_api_dashboard_id_00003',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiCloudDash000004',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=121, null=True)),
                ('vlrvda', models.FloatField(blank=True, null=True)),
                ('custovda', models.FloatField(blank=True, null=True)),
                ('vlrdev', models.FloatField(blank=True, null=True)),
                ('custodev', models.FloatField(blank=True, null=True)),
                ('vdaliq', models.FloatField(blank=True, null=True)),
                ('custoliq', models.FloatField(blank=True, null=True)),
                ('margem', models.FloatField(blank=True, null=True)),
                ('direto', models.FloatField(blank=True, null=True)),
                ('lucro', models.FloatField(blank=True, null=True)),
                ('perclucro', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ti_api_dashboard_id_00004',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiCloudDash000005',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlrvda', models.FloatField(blank=True, null=True)),
                ('vendedor', models.CharField(blank=True, db_collation='USING_NLS_COMP', max_length=80, null=True)),
            ],
            options={
                'db_table': 'ti_api_dashboard_id_00005',
                'managed': False,
            },
        ),
    ]
