# Generated by Django 4.2.4 on 2023-08-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_analytics_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiclouddash000001',
            options={'managed': False, 'verbose_name_plural': 'Ranking De Vendedores'},
        ),
    ]
