# Generated by Django 4.2.4 on 2023-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_analytics_api', '0002_alter_tiapidashboardid00001_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCloudDash000006',
            fields=[
                ('id', models.CharField(max_length=115, primary_key=True, serialize=False)),
                ('ldvlrvda', models.FloatField(blank=True, null=True)),
                ('ldcustovda', models.FloatField(blank=True, null=True)),
                ('ldlucro', models.FloatField(blank=True, null=True)),
                ('ldvlrdev', models.FloatField(blank=True, null=True)),
                ('ldcustodev', models.FloatField(blank=True, null=True)),
                ('ldvdaliq', models.FloatField(blank=True, null=True)),
                ('ldppdev', models.FloatField(blank=True, null=True)),
                ('ldcustoliq', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_cloud_dash_000006',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='apiclouddash000001',
            options={'managed': False, 'ordering': ['-vlrvda'], 'verbose_name_plural': 'Ranking De Vendedores'},
        ),
        migrations.AlterModelOptions(
            name='apiclouddash000002',
            options={'managed': False, 'ordering': ['regiao']},
        ),
        migrations.AlterModelOptions(
            name='apiclouddash000005',
            options={'managed': False, 'ordering': ['vendedor']},
        ),
        migrations.AlterModelTable(
            name='apiclouddash000001',
            table='api_cloud_dash_000001',
        ),
        migrations.AlterModelTable(
            name='apiclouddash000002',
            table='api_cloud_dash_000002',
        ),
        migrations.AlterModelTable(
            name='apiclouddash000003',
            table='api_cloud_dash_000003',
        ),
        migrations.AlterModelTable(
            name='apiclouddash000004',
            table='api_cloud_dash_000004',
        ),
        migrations.AlterModelTable(
            name='apiclouddash000005',
            table='api_cloud_dash_000005',
        ),
    ]
